name: 'blinkist_dbt_project'
version: '1.0.0'

profile: 'blinkist_dbt_project'

model-paths: ["models"]

seed-paths: ["seeds"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  blinkist_dbt_project:
    - name: mobile_events
      description: "Mobile events data"
      columns:
      - name: event_name
        description: "Name of the event"
        tests:
          - not_null
      - name: arrival_timestamp
        description: "Time the event arrived into the system"
        tests:
          - not_null
      - name: event_timestamp
        description: "Time the event was generated on the client's side"
        tests:
          - not_null
      - name: user_access_type
        description: "Type of user access. A user is either free or premium. 
          Premium means the user is using the payed version of the app while 
          free means using the unpayed version with less features"
        tests:
          - not_null

models:
  blinkist_dbt_project:
    staging:
      +materialized: incremental
    metrics:
      +materialized: view
    +materialized: table
